version: '2'
services:
  db:
    image: postgres:10
    environment:
     POSTGRES_PASSWORD: "olzeMyparol90"
     PGDATA: "/PG_DATA"
     POSTGRES_DB: image_manager
    container_name: postgres
    restart: unless-stopped
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}"
    volumes:
      - ./Dockerfiles/001_data.sql:/docker-entrypoint-initdb.d/001_data.sql
      - "/var/PG_DATA:/PG_DATA"
    ports:
        - "5432:5432"
  web:
    build:
      context: ./
      dockerfile: ./Dockerfiles/Dockerfile
    container_name: image_manager
    restart: unless-stopped
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}"
    links:
      - db:db
    volumes:
      - ./static:/var/voltmobi/static
      - ./upload:/var/voltmobi/upload
      - ./config.py:/var/voltmobi/config.py:ro
    ports:
    - "8081:8080"
    command: run_image_manager ./config.py